---

- name: IOS Facts example
  hosts: cisco
  vars:
    creds:
      host: "{{ ansible_host }}"
      username: "{{ username }}"
      password: "{{ password }}"
  tasks:
    - ios_facts:
        # provider: "{{creds}}"
      tags: facts_only

    - debug:
        var: ansible_net_model

    - ios_command:
         # provider: "{{ creds }}"
         commands: show ip int brief
      register: output

    - debug:
      #  var: outputi
      #  look for a key stdout_lines in the output
        msg: "{{ output['stdout_lines'][0][5] }}"




