---

- name: CONFIGURE NXOS SWITCHES
  hosts: nxos
  gather_facts: no
  tasks:
    # - name: gather nxos facts through ssh
    #  nxos_facts:
    #    gather_subset: all

    #- name: gather nxos facts through nxapi
    #  nxos_facts:
    #    provider: "{{ provider_nxapi }}"
    #    gather_subset: all
   
    - name: configure snmp parameters
      nxos_snmp_contact:
        provider: "{{ provider_nxapi }}"
        contact: "{{ snmp_contact }}"
      notify: write mem
      tags: snmp

    - name: configure snmp location
      nxos_snmp_location:
        provider: "{{ provider_nxapi }}"
        location: "{{ snmp_location }}"
        state: present
      notify: write mem
      tags: snmp
 
    - name: configure vlan
      nxos_vlan:
        provider: "{{ provider_nxapi }}"
        vlan_id: 560
        admin_state: up
        name: APP
        transport: nxapi
      notify: write mem
      tags: vlan

    - name: configure a range of vlans from a list
      nxos_vlan:
        provider: "{{ provider_nxapi }}"
        vlan_id: "{{ item.vlan_id }}"
        admin_state: "{{ item.admin_state }}"
        name: "{{ item.name }}"
      with_items: "{{ vlans }}"
      notify: write mem
      tags: vlan

    - name: configure ip interface
      nxos_l3_interface:
        provider: "{{ provider_nxapi }}"
        name: "{{ item.name }}"
        ipv4: "{{ item.ipv4 }}"
        state: "{{ item.state }}"
      with_items: "{{ l3int }}" 
      notify: write mem
      tags: ip_int

    - name: Test reachability
      nxos_ping:
        provider: "{{ provider_nxapi }}"
        dest: "{{ item.remote_ip }}"
        vrf: default
        host: "{{ ansible_host }}" 
      with_items: "{{ l3int }}"
      tags: ping

  handlers:
    - name: write mem 
      nxos_command:
        provider: "{{ provider_ssh }}"
        commands: copy run start
      changed_when: True
      tags: wr_mem
