---

creds_ssh: 
  host: "{{ ansible_host }}" 
  username: "{{ username }}" 
  password: "{{ password }}" 
  transport: cli 
  timeout: 60 


creds_eapi: 
  host: "{{ ansible_host }}" 
  username: "{{ vault_ansible_user }}" 
  password: "{{ vault_ansible_pass }}" 
  transport: eapi 
  use_ssl: True 
  validate_certs: no 

global_config:
  - "ip domain-name {{ default_domain }}"
  - "ip name-server vrf default {{ name_server1 }}"
  - "ip name-server vrf default {{ name_server2 }}"
  - "ntp server {{ ntp1 }}"
  - "ntp server {{ ntp2 }}"
  - "ip route 1.1.1.1/32 {{default_gateway }}"
  - "ip route 1.1.1.11/32 {{default_gateway }}"
  - "ip route 1.1.1.21/32 {{default_gateway }}"
  - "ip route 1.1.1.31/32 {{default_gateway }}"
